server:
  port: ${project.prot}
  servlet:
    multipart:
      #单文件上传最大大小，默认100Mb
      max-request-size: 100Mb
      #多文件上传时最大大小,默认1000Mb
      max-file-size: 1000Mb
    session:
      #session过期时间
      timeout: 600s
  #这些配置是为了支持https
  use-forward-headers: true
  tomcat:
    #这些配置是为了支持https
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
    remote-ip-header: x-forwarded-for
logging:
  config: classpath:logback-spring.xml

spring:
  #配置文件列表
  profiles:
    active: dev
  #系统缓存
  cache:
    type: redis
  #Druid连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://${jdbc.host}/${jdbc.database}?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: ${jdbc.user}
      password: ${jdbc.pass}
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 5
      maxActive: 200
      # 配置获取连接等待超时的时间(毫秒)
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 100000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000

      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
  #redis缓存
  redis:
    database: 0
    # Redis服务器地址
    host: ${redis.host}
    # Redis服务器连接端口
    port: ${redis.port}
    # 连接超时时间
    timeout: 10s
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3s
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
  session:
    #选择使用redis 作为session存储
    store-type: redis

  devtools:
    restart:
      #排除修改后不用热启动
      exclude: static/**
      enabled: false
  mvc:
    favicon:
      #关闭默认favicon.ico
      enabled: false
  thymeleaf:
    cache: false
    enabled: false
  jackson:
    date-format: ${project.date-format} ${project.time-format}
    time-zone: GMT+8
#mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:xyz/**/*Mapper.xml
  type-aliases-package: xyz.ersut.entity
  config-location: classpath:mybitis-config.xml